version: '3.8'
services:
  mongodb:
    image: mongo
    env_file: ./.env
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword

volumes:
  mongodb_data:
